# Generated by Django 3.0.3 on 2020-03-13 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Board', '0004_auto_20200313_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='creator',
        ),
        migrations.AddField(
            model_name='likes',
            name='author',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
